version: '3'
services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0' #-pで公開するポート番号、-bでバインドするIPアドレス
    volumes:
      - .:/app　#/appにマウント。
    ports:
      - 3000:3000 #コンテナ外部のポート番号:内部
    depends_on:
      - db #先にdbが起動
    tty: true #pryでデバッグするために必要
    stdin_open: true
  db:
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql #PC上の領域にデータを保存することで、コンテナを削除しても残る
    environment:
      MYSQL_ROOT_PASSWORD: password #環境変数の設定。OS上で保持される変数のこと
volumes:
  db-volume:
